### ISSUE TITLE
How does it compare to as_barcode?

### ISSUE THREAD

**Issue by kukimik** [zorantica/qr-code#11]
Do you know how `ZT_QR` compares to Anton Scheffer's https://github.com/antonscheffer/as_barcode (apart from the latter generating a larger variety of barcodes and of the obvious differences in the API)? Are you aware of any pros/cons of the packages?

**Comment by zorantica** [comment]
I'm aware of Anton's package but I never tested it.
Honestly, by the name of the package and the repository, I though it can produce barcodes only. 
But now I can see it can produce QR codes too.

**Comment by kukimik** [comment]
Ok, thanks for answering!
