### ISSUE TITLE
Some urls don't get the correct qr code

### ISSUE THREAD

**Issue by brankosibalic** [zorantica/qr-code#2]
HI,

I am having a problem with qr code generation. We use oracle 10g so I had to change two functions which are not supported, like the guy that had a problem with 11g in the issue mentioned before. It is working most of the time, but there is a problem with longer urls. The qr code is not readable or it is reading totally wrong ( some random numbers instead of url). Can you provide any help? I compared debug info from your demo site and my database and data is the same, but final message is not.

**Comment by zorantica** [comment]
Hi,

It seems like there is a problem with Your database encoding.
QR codes are using UTF-8 encoded strings which are native for newer
databases.
If Your database is using different encoding You should use CONVERT
function to change encoding of string, which is going to be encoded into
QR code, to UTF8.

Please try to implement this and let me know if it works.

Best regards,
Zoran

**Comment by brankosibalic** [comment]
We are using utf-8. I tried with convert, and getting the same result.
![photo_2020-11-30_12-53-08](https://user-images.githubusercontent.com/75249607/100607542-5e9df880-330b-11eb-801e-710419987b2d.jpg)

I am comparing debug data from your demo site, and everything is the same until final message is generated. The length is different at that point. Here is screenshot of debug compassion
![compare](https://user-images.githubusercontent.com/75249607/100607808-c8b69d80-330b-11eb-83ba-840a2371114f.jpg)
:

**Comment by brankosibalic** [comment]
I found what was causing this random problem. It was the function that converts integer to binary I had to replace with 10g supported version. It was returning null when 0 was passed in as parameter. I fixed it and now it is working as it should.

**Comment by zorantica** [comment]
Fantastic! Thanks for the tip!

Best regards,
Zoran
