### ISSUE TITLE
insert into database as null 

### ISSUE THREAD

**Issue by nesmasoliman** [zorantica/qr-code#3]
hey zorantica, 

Thank you for the amazing plugin . I applied it on apex and was trying to save the QR code as an image but it saves into the database as null. I tried once as html table and another time as the bmp image... any tips on that ?

**Comment by zorantica** [comment]
Hi!

This plugin is read-only and it only displays rendered QR code images on
the page.
It does not store images back in the database.

But You can easily achieve this using the QR Code database package which
comes together with a plugin.
There is a function which returns an image as BLOB content and You can save
this BLOB in the desired database table and column.
The function is named "f_qr_as_bmp" and it is easy to use. It uses similar
parameters as for APEX plugin - data to be encoded, error correction level
and (optionally) margins or not..
