### ISSUE TITLE
Image size BMP

### ISSUE THREAD

**Issue by jvhe123** [zorantica/qr-code#6]
Hi

Is it possible to define the image-size of the bmp-image? 
The generated bmp-images are too large. I would like to get smaller dimensions.

I use following code :

`DECLARE
  barcode  blob;
BEGIN
  barcode := f_bmp2jpg(ZT_QR.f_qr_as_bmp('My data' , 'L', 'N'));
  
  zt_qr.p_save_file( barcode, 'mybarcode.jpg', 'BARCODE_DIR');
  
END; `

**Comment by zorantica** [comment]
Hi!

No, for BMP image currently it is not possible.
Module size is with fixed size of 8x8 px.

If Your client software for displaying QR code supports SVG images or HTML code then You can use those solutions
Functions for generating QR code as SVG or HTML contain module size as input parameter.

Another option is to display BMP image smaller by defining it's dimensions in Your client software (of course - if this is supported).

**Comment by eehabsaid** [comment]
can we do the same for Barcode?

**Comment by eehabsaid** [comment]
can we do the same for Barcode?
I mean is there another PLSQL code to generate Barcode?

**Comment by zorantica** [comment]
Hi!

This package is made for QR codes only... for barcodes I don't have a
solution developed.

If I may ask, which tool are You using for displaying a barcode?
Barcodes are pretty simple, there is no such complex calculations involved
as for QR codes.
On the internet there are plenty of True Type fonts which can be
easily installed and used to display barcodes... that's why I'm asking
about a way You're displaying them.


Best regards,
Zoran

**Comment by eehabsaid** [comment]
Hi,
thanks for your kind response.
indeed I am displaying it on Oracle Reports which might contains Arabic characters and Hindi numbers,
and when using traditional barcode fonts, it displays it on the report as barcode, but doesn't work (with barcode reader tools),
so, this is why I asked for barcode solution which can generate barcode as a picture.

**Comment by zorantica** [comment]
Hi!

For Oracle Reports there are other solutions provided, for example Java or
PLL library

https://www.idautomation.com/barcode-components/java/oracle-reports/
https://www.idautomation.com/font-encoders/oracle-reports/

You may try one of those. It should not be a problem to install / implement
them.


Best regards,
Zoran

**Comment by eehabsaid** [comment]
Thank you.
but IDAutomation is not free regarding the java solution, but free with PLSQL code which use the font, but as mentioned above, the font doesn't work with Arabic characters and Hindi numbers.

**Comment by zorantica** [comment]
Quick question - do You need to encode only numbers in the barcode or
letters too? You mentioned Arabic characters and Hindi numbers in Your
previous email.

Best regards,
Zoran

**Comment by eehabsaid** [comment]
Both

**Comment by zorantica** [comment]
Been thinking about one solution if You are in position to implement it.
What if... You pre-prepare barcode images and store them in the
database BEFORE a report is produced, by calling some external services for
barcode generation?
I know this is not a pure and simple PL/SQL solution but in the end it can
be a solution.

One question out of topic... have You considered replacing Oracle Reports
with some other documentation / reporting tool like APEX Office Print,
Jasper Reports or Oracle BI?
APEX Office Print has a built-in solution for barcode and QR code
generation. Plus, it is pretty simple to install and use.
Oracle Reports are not supported any more and they are slowly going into
history...


Best regards,
Zoran

**Comment by eehabsaid** [comment]
Yes, I have already made a java solution to generate Barcode and QRCode as image, not only that,
It can (store it in the database directly, save it to a file on the HD of the server, or get it in an in-line query,
I wonder if you could take a look at this link:

https://drive.google.com/file/d/1-Mcpc8pQJ56CTOODq6siHQZIR1fnAuMk/view?usp=sharing

As for other reporting tools: It depends on the client's requirements and budget.

Thanks,
Ehab

**Comment by zorantica** [comment]
Yes of course, JAVA in the database is also a solution.
The only issue with JAVA can be backward compatibility for older databases.
Thay have older JAVA in the database installed... 11g has I think JAVA 1.5.

Otherwise, a nice solution. It can be easily used in PL/SQL.


Best regards,
Zoran
